Handling imbalance dataset

upsampling and downsampling

In [1]:
import numpy as np
import pandas as pd

np.random.seed(123) ### Whenever  randomly selecting some values it should not change

n_samples=1000

class_0_ratio = 0.9

n_class_0=int(n_samples*class_0_ratio)
n_class_1=n_samples-n_class_0

In [2]:
n_class_0,n_class_1

(900, 100)

In [11]:
###Create Data frame with imbalanced dataset

class_0 = pd.DataFrame({
    'feature_1':np.random.normal(loc=0,scale=1,size=n_class_0),
    'feature_2':np.random.normal(loc=0,scale=1,size=n_class_0),
    'target':[0]*n_class_0

})

class_1 = pd.DataFrame({
    'feature_1':np.random.normal(loc=2,scale=1,size=n_class_1),
    'feature_2':np.random.normal(loc=2,scale=1,size=n_class_1),
    'target':[1]*n_class_1

})

In [12]:
df=pd.concat([class_0,class_1]).reset_index(drop=True)

In [13]:
df.head()

   feature_1  feature_2  target
0  -0.471276   0.328462       0
1   1.084072   1.038230       0
2  -0.379223   1.147064       0
3  -0.362274   0.638254       0
4  -0.681071  -1.075766       0

In [14]:
df.tail()

     feature_1  feature_2  target
995   2.720690   1.978489       1
996   1.949078   3.709793       1
997   2.709784   3.324917       1
998   1.817689   1.549237       1
999   2.838910   2.240773       1

In [ ]:

df['target'].value_counts()

target
0    900
1    100
Name: count, dtype: int64

In [18]:
###upsampling

df_minority=df[df['target']==1]
df_majority=df[df['target']==0]


from sklearn.utils import resample

df_minority_upsampled = resample(df_minority, replace=True,n_samples=len(df_majority),random_state=42)

In [19]:
df_minority_upsampled.shape

(900, 3)

In [20]:
df_minority_upsampled.head()

     feature_1  feature_2  target
951   2.701255   0.056481       1
992   2.322342   3.289170       1
914   2.500618   1.338170       1
971   1.922944   2.907951       1
960   0.630218   0.982405       1

In [21]:
df_upsampled=pd.concat([df_majority,df_minority_upsampled])

In [22]:
df_upsampled['target'].value_counts()

target
0    900
1    900
Name: count, dtype: int64